version: "3"
services:
  liftlogger:
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
    container_name: liftlogger
    ports:
      - 9010:9010
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: always
    volumes:
      - ./:/app